// Generated by tools/generate-encodings.py; do not edit tables by hand.
const encodings = Object.freeze({"ascii": 0, "cp437": 1, "cp850": 2, "cp852": 3, "cp858": 4, "cp866": 5, "windows1250": 6, "windows1251": 7, "windows1252": 8});
const codepageProfiles = Object.freeze({
  manual: Object.freeze({"cp437": 0, "cp850": 2, "windows1252": 16, "cp866": 17, "cp852": 18, "cp858": 19}),
  legacy: Object.freeze({"cp437": 0, "cp850": 2, "cp852": 13, "cp858": 14, "cp866": 12, "windows1250": 50, "windows1251": 51, "windows1252": 11}),
});
module.exports = { encodings, codepageProfiles };
