#!/usr/bin/env python3
"""Generate identical Unicode mappings for C and browser from Python codecs.

No printer selector is inferred from an encoding. Selector profiles below are
separate: manual 1.00 section 2.40 and the repository's historical numbering.
"""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
codecs = ['cp437', 'cp850', 'cp852', 'cp858', 'cp866', 'windows1250', 'windows1251', 'windows1252']
tables = {}
for name in codecs:
    codec = name.replace('windows', 'cp')
    table = []
    for byte in range(128, 256):
        try:
            table.append(ord(bytes([byte]).decode(codec)))
        except UnicodeDecodeError:
            table.append(0xffff)
    tables[name] = table

manual = dict(cp437=0, cp850=2, windows1252=16, cp866=17, cp852=18, cp858=19)
legacy = dict(cp437=0, cp850=2, cp852=13, cp858=14, cp866=12, windows1250=50, windows1251=51, windows1252=11)
ids = {name: i for i, name in enumerate(['ascii'] + codecs)}
banner = '// Generated by tools/generate-encodings.py; do not edit tables by hand.\n'
c = banner + 'static const uint16_t munbyn_encoding_tables[8][128] = {\n'
for name, table in tables.items():
    c += '    { /* ' + name + ' */\n'
    for i in range(0, 128, 8):
        c += '        ' + ', '.join(f'0x{v:04X}' for v in table[i:i+8]) + ',\n'
    c += '    },\n'
c += '};\n'
(root/'src/munbyn_encoding_tables.inc').write_text(c)
profiles = ('const codepageProfiles = Object.freeze({\n'
            f'  manual: Object.freeze({json.dumps(manual)}),\n'
            f'  legacy: Object.freeze({json.dumps(legacy)}),\n'
            '});\n')
(root/'packages/node/lib/encoding.js').write_text(banner +
    f'const encodings = Object.freeze({json.dumps(ids)});\n' + profiles +
    'module.exports = { encodings, codepageProfiles };\n')
ts = banner + 'export type TextEncoding = ' + ' | '.join(repr(n) for n in ids) + ';\n'
ts += 'export ' + profiles
ts += 'const tables: Record<TextEncoding, readonly number[]> = ' + json.dumps({'ascii': [], **tables}) + ';\n'
ts += '''
/** Strict single-byte encoding; no replacement characters or silent UTF-8. */
export function encodeText(text: string, encoding: TextEncoding): Uint8Array {
  if (typeof text !== 'string' || !Object.prototype.hasOwnProperty.call(tables, encoding)) {
    throw new TypeError('Expected text and a supported encoding');
  }
  const table = tables[encoding];
  const output: number[] = [];
  for (const character of text) {
    const scalar = character.codePointAt(0)!;
    if (scalar < 128) {
      if ((scalar < 32 && ![9, 10, 13].includes(scalar)) || scalar === 127) {
        throw new RangeError('Encoded text permits only printable characters, LF, CR and HT');
      }
      output.push(scalar);
    } else {
      const index = table.indexOf(scalar);
      if (index < 0 || scalar === 0xffff) {
        throw new RangeError(`Character U+${scalar.toString(16).toUpperCase()} is not representable in ${encoding}`);
      }
      output.push(index + 128);
    }
  }
  return new Uint8Array(output);
}
'''
(root/'packages/web/src/encoding.ts').write_text(ts)
